apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-gateway.fullname" . }}
  labels:
    app: {{ template "radar-gateway.name" . }}
    chart: {{ template "radar-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gateway.yml: |
    # Resource config class
    #resourceConfig: org.radarbase.gateway.inject.ManagementPortalEnhancerFactory

    server:
      baseUri: http://0.0.0.0/radar-gateway/

    kafka:
      producer:
        bootstrap.servers: {{ .Values.bootstrapServers }}
        {{- if .Values.cc.enabled }}
        admin:
            bootstrap.servers: {{ .Values.bootstrapServers }}
            security.protocol: SASL_SSL
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ .Values.cc.apiKey }}" password="{{ .Values.cc.apiSecret }}";
            ssl.endpoint.identification.algorithm: https
            sasl.mechanism: PLAIN
        {{ end }}
      serialization:
        schema.registry.url: {{ .Values.schemaRegistry }}
        {{- if .Values.cc.enabled }}
        schema.registry.basic.auth.user.info: {{ .Values.cc.schemaRegistryApiKey }}:{{ .Values.cc.schemaRegistryApiSecret }}
        {{ end }}
    auth:
      managementPortalUrl: http://{{ .Values.managementportalHost }}:8080/managementportal
