apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-restapi.fullname" . }}
  labels:
    app: {{ template "radar-restapi.name" . }}
    chart: {{ template "radar-restapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  radar.yml: |
    # Mongodb hosts a map of hostname and port
    mongodb_hosts:
        {{ .Values.mongodb.host }}: 27017

    # Mongodb User
    mongodb_credentials:
        username: {{ .Values.mongodb.username }}
        password: {{ .Values.mongodb.password }}
        database_name: {{ .Values.mongodb.database_name }}

    management_portal_config:
        oauth_client_id: radar_restapi #OAuth2 clientId used by the webApp for making requests
        oauth_client_secret: secret #OAuth2 client secret
        oauth_client_scopes: SUBJECT.READ PROJECT.READ SOURCE.READ SOURCETYPE.READ SOURCEDATA.READ
        management_portal_url: http://{{ .Values.managementportal_host }}:8080/managementportal/ #URL pointing Management Portal
        token_endpoint: oauth/token #URL managing tokens
        project_endpoint: api/projects/ #URL managing project function
        subject_endpoint: api/subjects/
        source_type_endpoint: api/source-types/
        source_data_endpoint: api/source-data/
        source_endpoint: api/sources/

    # Timeout duration for every source-type to decide source status whether its connected or not.
    # A source-type should be defined by following the convention of producer_model as mentioned in
    # the specification in radar-schemas
    # timeout should be specified as the ISO-8601 duration format {@code PnDTnHnMn.nS}.
    source-type-connection-timeout:
        android_phone: PT2H
        empatica_e4: PT1H
