apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "ceph.fullname" . }}
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: {{ .Release.Namespace }}.cephfs.csi.ceph.com
parameters:
  # clusterID is the namespace where operator is deployed.
  clusterID: {{ .Release.Namespace }}

  # CephFS filesystem name into which the volume shall be created
  fsName: {{ include "ceph.fullname" . }}

  # Ceph pool into which the volume shall be created
  # Required for provisionVolume: "true"
  pool: {{ include "ceph.fullname" . }}-data0

  # Root path of an existing CephFS volume
  # Required for provisionVolume: "false"
  # rootPath: /absolute/path

  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}

reclaimPolicy: Retain
