clusterName: "elasticsearch"

replicas: 3
minimumMasterNodes: 2

esMajorVersion: "7"

esJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "1000m"
    memory: "1.5Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  resources:
    requests:
      storage: 30Gi


# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "best effort"
