apiVersion: v1
appVersion: "3.2.0"
description: A Helm chart for the front-end application of RADAR-base Rest Sources Authorizer which is a portal to authorize the Fitbit connector to read data from Fitbit accounts.
name: radar-rest-sources-authorizer
version: 0.2.0
sources: ["https://github.com/RADAR-base/RADAR-Rest-Source-Auth"]
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: keyvan@thehyve.nl
    name: Keyvan Hedayati
    url: https://www.thehyve.nl
  - email: joris@thehyve.nl
    name: Joris Borgdorff
    url: https://www.thehyve.nl/experts/joris-borgdorff
  - email: nivethika@thehyve.nl
    name: Nivethika Mahasivam
    url: https://www.thehyve.nl/experts/nivethika-mahasivam
