apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-backend.fullname" . }}
  labels:
    app: {{ template "radar-backend.name" . }}
    chart: {{ template "radar-backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  radar.yml: |
    version: 1.0
    released: 2018-09-13

    #============================== Zookeeper ==============================#
    #List of Zookeeper instances
    zookeeper:
        - host: {{ first (splitList ":" .Values.zookeeper) }}
          port: {{ last (splitList ":" .Values.zookeeper) }}

    #================================ Kafka ================================#
    #List of Kafka brokers
    broker:
        - host: {{ first (splitList ":" .Values.kafka) }}
          port: {{ last (splitList ":" .Values.kafka) }}

    #=========================== Schema Registry ===========================#
    #List of Schema Registry instances
    schema_registry:
        - host: {{ first (splitList ":" .Values.schema_registry) }}
          port: {{ last (splitList ":" .Values.schema_registry) }}
          protocol: http
    #=========================== Kafka REST Proxy ===========================#
    #List of kafka Rest proxy instances
    rest_proxy:
        host: {{ first (splitList ":" .Values.rest_proxy) }}
        port: {{ last (splitList ":" .Values.rest_proxy) }}
        protocol: http

    #Kafka internal parameters
    #============================ Kafka Streams ============================#
    #The number of threads that a stream must be run according is priority
    stream:
      threads_per_priority:
        low: 1
        normal: 2
        high: 4

      properties:
        max.request.size: 3500042 #Set message.max.bytes for kafka brokers higher than or equal to this value
        retries: 15
        session.timeout.ms: 500000
        commit.interval.ms: 300000
        request.timeout.ms: 10860000
        state.cleanup.delay.ms: 10860000

      streams:
        - class: org.radarcns.stream.empatica.E4AccelerationStream
        - class: org.radarcns.stream.empatica.E4BatteryLevelStream
        - class: org.radarcns.stream.empatica.E4BloodVolumePulseStream
        - class: org.radarcns.stream.empatica.E4ElectroDermalActivityStream
        - class: org.radarcns.stream.empatica.E4HeartRateStream
        - class: org.radarcns.stream.empatica.E4InterBeatIntervalStream
        - class: org.radarcns.stream.empatica.E4TemperatureStream
        - class: org.radarcns.stream.phone.PhoneAccelerationStream
        - class: org.radarcns.stream.phone.PhoneBatteryStream
        - class: org.radarcns.stream.phone.PhoneUsageStream
        - class: org.radarcns.stream.phone.PhoneUsageAggregationStream


      #====================== Source statistics monitor ======================#
      source_statistics:
        - name: Empatica E4
          topics:
          - android_empatica_e4_blood_volume_pulse_1min
          output_topic: source_statistics_empatica_e4
        - name: Biovotion VSM1
          topics:
          - android_biovotion_vsm1_acceleration_1min
          output_topic: source_statistics_biovotion_vsm1
        - name: RADAR pRMT
          topics:
          - android_phone_acceleration_1min
          - android_phone_bluetooth_devices
          - android_phone_sms
          - android_phone_call
          - android_phone_contacts
          - android_phone_usage_event
          - android_phone_relative_location
          output_topic: source_statistics_android_phone

    #======================== Battery level monitor ========================#
    battery_monitor:
      level: LOW
      notify: # Each project can have a number of email addresses
        - project_id: s1
          email_address:
            - notifier1@email
        - project_id: s2
          email_address:
            - notifier2@email
      email_host: smtp
      email_port: 25
      email_user: user@example.com
      topics:
        - android_empatica_e4_battery_level

    #======================= Disconnection monitor==========================#
    disconnect_monitor:
      notify: # Each project can have a number of email addresses
        - project_id: s1
          email_address:
            - notifier1@email
        - project_id: s2
          email_address:
            - notifier2@email
      email_host: smtp
      email_port: 25
      email_user: user@example.com
      topics:
        - android_empatica_e4_temperature
      timeout: 1800  # seconds after which a stream is set disconnected
      alert_repetitions: 2  # number of additional emails to send after the first

    #====================== Source statistics monitor ======================#
    statistics_monitors:
      - name: Empatica E4
        topics:
          - android_empatica_e4_blood_volume_pulse_1min
        output_topic: source_statistics_empatica_e4
      - name: Biovotion VSM1
        topics:
          - android_biovotion_vsm1_acceleration_1min
        output_topic: source_statistics_biovotion_vsm1
      - name: RADAR pRMT
        topics:
          - android_phone_acceleration_1min
          - android_phone_bluetooth_devices
          - android_phone_sms
          - android_phone_call
          - android_phone_contacts
          - android_phone_usage_event
          - android_phone_relative_location
        output_topic: source_statistics_android_phone

    persistence_path: /var/lib/radar/data
